### ISSUE TITLE
Better types

### ISSUE THREAD

**Issue by creepinson** [cenguidanos/node-markdown-parser#5]
The current typings use "any' as the final json type. This means that I can't get autocomplete for the built in types as seen in https://node-markdown-parser.onrender.com/.

![image](https://user-images.githubusercontent.com/11761863/102400954-6ca07a00-3f97-11eb-93b7-d4e5e2078625.png)

I could make a PR for this if you want me to do that, but my solution would be to change the following near [toJSON](https://github.com/cenguidanos/node-markdown-parser/blob/3db87d96504ecf6509c0fd39a069ae3cfe98d68a/src/parsers/markdown.ts#L75).

```typescript
  public toJSON(file: any): any {
    if (Array.isArray(file)) {
      return this.processMultipleFileJSON(file);
    } else {
      return this.processSingleFileJSON(file);
    }
  }
```

to use a custom type with generics liek so:

```typescript

  public toJSON<T = Record<string, unknown>>(file: any): MarkdownJSON<T> {
    if (Array.isArray(file)) {
      return this.processMultipleFileJSON(file);
    } else {
      return this.processSingleFileJSON(file);
    }
  }
...

export type FileExtension = ".md" | ".csv" | ".xml" | ".yml"
export type TableOfContents = Array<{
  id: string;
  depth: 1;
  text: string;
}>
export type MarkdownJSON<T> = T & {
  title: string;
  subtitle: string;
  extension: FileExtension;
  updatedAt: number;
  toc: TableOfContents;
  body: string;
}
```

This is just out of the top of my head but it should be close to what you'd need.

**Comment by creepinson** [comment]
With this solution you could do something like:

```typescript
import { readFileSync } from  "fs";
import { Markdown, MarkdownParserOptions } from "@cenguidanos/node-markdown-parser";

let markdownOptions: MarkdownParserOptions;

let markdown: Markdown = new Markdown(markdownOptions);

let file: string = readFileSync("./markdown/example.md", "utf-8");

let data = markdown.toJSON<{custom: string}>({file, custom: "hello world"});

// you can let your ide autocomplete ".body"
console.log(data.body);


```

**Comment by cenguidanos** [comment]
Hi @creepinson, do it yourself, make a PR. But, remember that we need to return sometimes an array of `MarkdownJSON<T>`.

Thanks,

**Comment by creepinson** [comment]
#6

**Comment by cenguidanos** [comment]
Good job! Tomorrow i'll update npm registry and docs. Thnks.
